Update response payload structure
pangeacyber/go-pangea pull request #22
Opened 2022-09-07 00:21 UTC by mcombspangea

Pangea has removed `status_code` from their response payloads in favor of a custom `status` field which is an enum defined in their API docs.

2022-09-07 17:32 UTC, pangea-andrest requested changes

2022-09-07 17:32 UTC, pangea-andrest commented on pangea/pangea_test.go
> +	assert.NotNil(t, *resp.Status)
Dereference before check it's not nil

2022-09-08 18:44 UTC, pangea-andrest commented on pangea/pangea_test.go
>  	assert.NotNil(t, *resp.Status)
I feel that in this line it should be `assert.NotEmpty(t, *resp.Status)`. 
Sorry if I wasn't clear at first time.  Just to clarify we should need both checks:
```
	assert.NotNil(t, resp.Status)
	assert.NoEmpty(t, *resp.Status)
```

2022-09-08 18:48 UTC, mcombspangea commented on pangea/pangea_test.go
>  	assert.NotNil(t, *resp.Status)
Should just do an equality check after notnil. This shouldn't be a pointer but we can refactor that later.

2022-09-08 18:56 UTC, pangea-andrest approved these changes

2022-09-08 18:56 UTC, merged